### ISSUE TITLE
Bug in calibration on the simulated system

### ISSUE THREAD

**Issue by romainbrette** [romainbrette/holypipette#65]
I got this:

Traceback (most recent call last):
  File "/Users/Romain/PyCharmProjects/holypipette/holypipette/interface/base.py", line 186, in execute
    func()
  File "/Users/Romain/PyCharmProjects/holypipette/holypipette/devices/manipulator/calibratedunit.py", line 653, in calibrate
    move_stage=move_stage)
  File "/Users/Romain/PyCharmProjects/holypipette/holypipette/devices/manipulator/calibratedunit.py", line 480, in move_and_track
    x, y, z = self.locate_pipette()
  File "/Users/Romain/PyCharmProjects/holypipette/holypipette/devices/manipulator/calibratedunit.py", line 417, in locate_pipette
    xt, yt, val = templatematching(image, template)
  File "/Users/Romain/PyCharmProjects/holypipette/holypipette/vision/templatematching.py", line 39, in templatematching
    res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)
error: OpenCV(3.4.1) /opt/conda/conda-bld/opencv-suite_1530774556719/work/modules/imgproc/src/templmatch.cpp:1107: error: (-215) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function matchTemplate

Something to do with template matching.

**Comment by romainbrette** [comment]
I think it's just because I didn't center the pipette...
