### ISSUE TITLE
Calibration bug

### ISSUE THREAD

**Issue by romainbrette** [romainbrette/holypipette#78]
We just got this while trying to calibrate:

2018-11-02 14:38:36,055 ERROR Task "calibrate" failed [holypipette.interface.pipettes - thread 13356]
Traceback (most recent call last):
  File "C:\Users\Romain\PycharmProjects\holypipette\holypipette\interface\base.py", line 231, in _execute_single_task
    func()
  File "C:\Users\Romain\PycharmProjects\holypipette\holypipette\devices\manipulator\calibratedunit.py", line 559, in calibrate
    self.stage.calibrate()
  File "C:\Users\Romain\PycharmProjects\holypipette\holypipette\devices\manipulator\calibratedunit.py", line 987, in calibrate
    self.relative_move(distance, axis) # there could be a keyword blocking = True
  File "C:\Users\Romain\PycharmProjects\holypipette\holypipette\devices\manipulator\manipulatorunit.py", line 81, in relative_move
    self.dev.relative_move(x, self.axes[axis])
  File "C:\Users\Romain\PycharmProjects\holypipette\holypipette\devices\manipulator\luigsneumann_SM10.py", line 224, in relative_move
    self.relative_move_group([x], [axis], fast=fast) # why not using the specific command?
  File "C:\Users\Romain\PycharmProjects\holypipette\holypipette\devices\manipulator\luigsneumann_SM10.py", line 299, in relative_move_group
    self.send_command(ID, [0xA0] + axes4 + pos, -1)
  File "C:\Users\Romain\PycharmProjects\holypipette\holypipette\devices\manipulator\luigsneumann_SM10.py", line 137, in send_command
    raise serial.SerialException(msg)
SerialException: Expected answer '06a04b', got '' instead

**Comment by mstimberg** [comment]
Oh, this seems to be something that I screwed up with a recent change (meant to make things more robust...). I can make the change, or are you currently doing stuff on the code?

If yes, all that should be needed is to change this line: https://github.com/romainbrette/holypipette/blob/master/holypipette/devices/manipulator/luigsneumann_SM10.py#L114
from 
```Python
if nbytes_answer == 0:
```
into
```Python
if nbytes_answer <= 0:
```
Sorry about this...
